### ISSUE TITLE
"python main.py" and "python app.py" do the same thing (venv on windows)

### ISSUE THREAD

**Issue by InfernalDread** [Josh-XT/Agent-LLM#10]
As the title implies, the "python main.py" command no longer initializes the Agent, rather it does the same job as the app.py. Not sure if this was intentional, but I cannot run the program anymore because of this.

**Comment by Josh-XT** [comment]
Yeah, main.py just runs the Flask API now.  Functionality is growing too fast to play in a terminal.

If you want to run the task runner (babyagi) in the terminal only:
```
python babyagi.py "Your objective"
```

If you want to run Agent-LLM in terminal only:
```
python AgentLLM.py --prompt "Your prompt"
```

The reason `main.py` was changed is because the focus is going to be on this being a back end api and web app more than a terminal app.

The web app is improving a lot.  Not done yet, but it is going well.  Give it another look if you haven't in the past 5 minutes.

**Comment by InfernalDread** [comment]
oh ok sweet! I'll take a look!
