### ISSUE TITLE
GPU utilization

### ISSUE THREAD

**Issue by nbdy** [Josh-XT/Agent-LLM#227]
### Problem Description

I'd like to use my GPU with gpt4all and fastchat, this is, as far as I know, not implemented right now.

### Proposed Solution

Use the nvidia/cuda docker images and docker compose to pass a NVIDIA GPU to the backend or fastchat docker container.

### Additional Context

I've already implemented it in my fork, but I don't think it should be merged into main.

See [Dockerfile-backend-nvidia](https://github.com/nbdy/Agent-LLM/blob/fastchat/Dockerfile-backend-nvidia), [Dockerfile-fastchat](https://github.com/nbdy/Agent-LLM/blob/fastchat/Dockerfile-fastchat) and [docker-compose.yml](https://github.com/nbdy/Agent-LLM/blob/fastchat/docker-compose.yml).

I've also added a [gpt4allgpu](https://github.com/nbdy/Agent-LLM/blob/fastchat/provider/gpt4allgpu.py) provider.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
Thanks!  Planning to modify and add these in when time permits.  If you have any that will work with our current set up, feel free to do a pull request with them.

**Comment by localagi** [comment]
@Josh-XT Just a general question partly on topic here, due to i plan to add audio and image capabilites for local setup, how we manage requirements here? Do we need get and probably build any lib or keep it somehow lightweight for users only using the remote services?

I still do struggle the decision between using a local textchat (I want to use a LLM model) client and connecting it via API to Agent-LLM or running it within agentLLM directly (i would prefer the latter, less 3rd party servers and overhead, but we need some architecture, i will probably add [GPTQ-for-LLaMa](https://github.com/qwopqwop200/GPTQ-for-LLaMa) some time in the future)

**Comment by Josh-XT** [comment]
> @Josh-XT Just a general question partly on topic here, due to i plan to add audio and image capabilites for local setup, how we manage requirements here? Do we need get and probably build any single lib? Even when users only want to use remote services?
> 
> I still do struggle the decision between using a local textchat (I want to use a LLM model) client and connecting it via API to Agent-LLM or running it within agentLLM directly (i would prefer the latter, less 3rd party servers and overhead, but I do need an idea how to do it, i will probably add [GPTQ-for-LLaMa](https://github.com/qwopqwop200/GPTQ-for-LLaMa) some time in the future)

Hello, this is a conversation better had in our Discord or a GitHub discussion rather than in an issue.

**Comment by Josh-XT** [comment]
Thanks!  Added your files, things look good.
