### ISSUE TITLE
not found error 

### ISSUE THREAD

**Issue by kevzy** [Josh-XT/Agent-LLM#35]
hey im running it on mac M1 and after doing python3 app.py im getting Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
on browser

**Comment by Josh-XT** [comment]
Hello.  I would recommend trying to use docker rather than launching with python directly.  If you pull the latest and run python app.py or run it with docker, you can access the API docs at: 
http://localhost:5000/docs 

Then if you run the front end with the instructions from the readme, the terminal should give you the URL to it as well.

**Comment by Josh-XT** [comment]
Please see the updated docs in the `README.md` in the repository.  I've updated them to be clearer about running locally.

https://github.com/Josh-XT/Agent-LLM

**Comment by kevzy** [comment]
> Hello. I would recommend trying to use docker rather than launching with python directly. If you pull the latest and run python app.py or run it with docker, you can access the API docs at: http://localhost:5000/docs
> 
> Then if you run the front end with the instructions from the readme, the terminal should give you the URL to it as well.

hey, yeah I pulled the latest code now it's working
