### ISSUE TITLE
llama_generate: error: prompt is too long (2249 tokens, max 1996)

### ISSUE THREAD

**Issue by CRCODE22** [Josh-XT/Agent-LLM#76]
2023-04-25 05:23:47 system_info: n_threads = 8 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
2023-04-25 05:23:47 llama_generate: **error: prompt is too long (2249 tokens, max 1996)**
2023-04-25 05:23:47 llama_generate: seed = 1682393027

[Error1.txt](https://github.com/Josh-XT/Agent-LLM/files/11316170/Error1.txt)

**Comment by Josh-XT** [comment]
Your prompt is too long. You're trying to run every command enabled on a small language model which is not going to give you any kind of useful results. Narrow the scope and see below (copy/paste from a similar issue #73 )

Most of that will be playing with the prompts in the model-prompts folders for whichever model you want to set it to work with. You can create your own prompts with text files in a new model folder you make as well.

The prompt engineering done in most of our prompts were intended for use with OpenAI GPT3.5 and they work extremely well with that model and GPT4, but they're extremely verbose prompts that need to be in order to make the very large models do specific tasks. There are a lot less apologies and things to deal with "over riding" through prompting in the smaller models. You can likely get away with accomplishing the same thing through vastly reduced prompting.
